### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kumarkaiwalya**
suno code shi hai

### CODE REVIEW

**Comment by kumarkaiwalya** [comment]
hua kuch

**Comment by Ameesha9616** [comment]
> suno code shi hai

ok

**Comment by Ameesha9616** [comment]
ok

**Comment by kumarkaiwalya** [comment]
kaam kr raha hai

**Comment by Ameesha9616** [comment]
> kaam kr raha hai

Ha

**Pull request merged**
